import { Bank } from '../interfaces/bank.interface';

export const BANK_LIST: readonly Bank[] = [
  { name: 'BANCO DE VENEZUELA', code: '0102' },
  { name: 'BANCO VENEZOLANO DE CREDITO', code: '0104' },
  { name: 'BANCO MERCANTIL', code: '0105' },
  { name: 'BANCO PROVINCIAL', code: '0108' },
  { name: 'BANCO DEL CARIBE', code: '0114' },
  { name: 'BANCO EXTERIOR', code: '0115' },
  { name: 'BANCO CARONI', code: '0128' },
  { name: 'BANESCO', code: '0134' },
  { name: 'BANCO SOFITASA', code: '0137' },
  { name: 'BANCO PLAZA', code: '0138' },
  { name: 'BANGENTE', code: '0146' },
  { name: 'BANCO DEL PUEBLO', code: '0149' },
  { name: 'BANCO FONDO COMUN', code: '0151' },
  { name: '100% BANCO', code: '0156' },
  { name: 'BANCO DEL SUR', code: '0157' },
  { name: 'BANCO DEL TESORO', code: '0163' },
  { name: 'BANCO AGRICOLA', code: '0166' },
  { name: 'BANCRECER', code: '0168' },
  { name: 'MI BANCO', code: '0169' },
  { name: 'BANCO ACTIVO', code: '0171' },
  { name: 'BANCAMIGA', code: '0172' },
  { name: 'BANCO INTERNACIONAL DE DESARROLLO', code: '0173' },
  { name: 'BANPLUS', code: '0174' },
  { name: 'BANCO BICENTENARIO', code: '0175' },
  { name: 'BANFANB', code: '0177' },
  { name: 'N58 BANCO DIGITAL', code: '0178' },
  { name: 'BANCO NACIONAL DE CREDITO', code: '0191' },
  { name: 'BINANCE', code: 'BNB' },
] as const;
